name: Cleanup on PR Close

on:
  repository_dispatch:
    types: [pr-cleanup]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Cleanup PR Folder
        run: |
          BRANCH_DIR=fix-cleanup-workflow
          if [ -d "$BRANCH_DIR" ]; then
              git rm -rf "$BRANCH_DIR"
              git commit -m "Remove deployed PR: $BRANCH_DIR"
              git push
          else
              echo "Directory $BRANCH_DIR does not exist."
          fi
          exit 0
        shell: /usr/bin/bash -e {0}
