name: Deploy PR to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Get Branch Name
        id: get_branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF##*/})" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        if: github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ env.BRANCH_NAME }}

      - name: Clear PR Folder
        if: github.event.action == 'closed'
        run: |
          # Set up Git.
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Fetch all branches and tags. Necessary to operate on gh-pages.
          git fetch --prune --unshallow
          
          # Check out the gh-pages branch.
          git checkout gh-pages

          # Remove the directory named after the branch and check if it exists.
          BRANCH_DIR="${{ env.BRANCH_NAME }}"
          if [ -d "$BRANCH_DIR" ]; then
            git rm -rf "$BRANCH_DIR"
            
            # Commit and push the changes.
            git commit -m "Remove deployed PR: $BRANCH_DIR"
            git push origin gh-pages
          else
            echo "Directory $BRANCH_DIR does not exist on gh-pages."
          fi

