name: Trigger Cleanup on PR Close

on:
  pull_request:
    types: [closed]
    branches:
      - '*'

jobs:
  trigger-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: sergii-nosachenko/gud-food-good-ux
          event-type: pr-cleanup
          client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}"}'
